"""RoleBuffer → Terraform 코드 → 로컬 디스크"""
import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path

from .buffer import RoleBuffer
from .policy_fetcher import PolicyFetcher
from .policy_utils import is_aws_managed_policy, policy_arn_to_name

logger = logging.getLogger(__name__)


PROVIDERS_TF = """terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
}
"""

DATA_TF = """data "aws_ssoadmin_instances" "current" {}
"""


def sanitize_resource_name(name: str) -> str:
    return re.sub(r'[^a-zA-Z0-9_]', '_', name).lower()


def merge_inline_policies(
    customer_documents: list[tuple[str, dict]]
) -> dict:
    """
    여러 Customer Managed Policy 본문을 하나의 inline policy로 통합.
    
    IIC Permission Set은 Sid를 받지 않으므로 모든 Sid를 제거한다.
    Statement 순서는 보존 (원본 정책 순서 → 정책 내 순서).
    """
    merged_statements = []

    for policy_name, doc in customer_documents:
        statements = doc.get('Statement', [])

        # Statement는 dict 또는 list
        if isinstance(statements, dict):
            statements = [statements]

        for stmt in statements:
            # 원본 보호를 위해 복사 후 Sid 제거
            stmt_copy = {k: v for k, v in stmt.items() if k != 'Sid'}
            merged_statements.append(stmt_copy)

    return {
        'Version': '2012-10-17',
        'Statement': merged_statements,
    }

def generate_main_tf(
    buf: RoleBuffer,
    fetcher: PolicyFetcher,
    inline_max_chars: int,
) -> str:
    """
    RoleBuffer → main.tf 콘텐츠.
    
    AWS Managed → managed_policy_attachment (reference)
    Customer Managed → 본문 조회 → 통합 → permission_set_inline_policy
    """
    resource_name = sanitize_resource_name(buf.role_name)
    description = (
        f"Auto-generated from IAM Role '{buf.role_name}' "
        f"in account {buf.account_id}"
    )
    generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    sorted_policies = sorted(buf.policy_arns)

    # 1. AWS Managed와 Customer Managed 분리
    aws_managed = [p for p in sorted_policies if is_aws_managed_policy(p)]
    customer_managed = [p for p in sorted_policies if not is_aws_managed_policy(p)]

    # 2. Customer Managed 본문 조회 + 통합
    inline_doc = None
    if customer_managed:
        logger.info(
            f'Fetching {len(customer_managed)} customer managed policies '
            f'from account {buf.account_id}'
        )
        customer_documents = []
        for policy_arn in customer_managed:
            doc = fetcher.get_customer_policy_document(buf.account_id, policy_arn)
            customer_documents.append((policy_arn_to_name(policy_arn), doc))

        inline_doc = merge_inline_policies(customer_documents)
        inline_json = json.dumps(inline_doc, indent=2)

        if len(inline_json) > inline_max_chars:
            raise RuntimeError(
                f'Merged inline policy size ({len(inline_json)} chars) '
                f'exceeds limit ({inline_max_chars}). '
                f'Reduce customer managed policies or split Permission Set.'
            )

    # 3. Terraform 코드 생성
    parts = [
        f"# Auto-generated by Codegen Server at {generated_at}",
        f"# Source IAM Role: arn:aws:iam::{buf.account_id}:role/{buf.role_name}",
        f"# Requester IIC User: {buf.requester_iic_user}",
        f"# AWS Managed: {len(aws_managed)}, Customer Managed (inline): {len(customer_managed)}",
        "",
        # Permission Set
        f'resource "aws_ssoadmin_permission_set" "{resource_name}" {{',
        f'  name             = "{buf.role_name}"',
        f'  description      = "{description}"',
        f'  instance_arn     = tolist(data.aws_ssoadmin_instances.current.arns)[0]',
        f'  session_duration = "PT8H"',
        f'}}',
        "",
    ]

    # AWS Managed Policy attachments
    attachment_resource_names = []
    for policy_arn in aws_managed:
        policy_name = policy_arn_to_name(policy_arn)
        attach_res = f"{resource_name}_attach_{sanitize_resource_name(policy_name)}"
        attachment_resource_names.append(
            ('aws_ssoadmin_managed_policy_attachment', attach_res)
        )
        parts += [
            f'resource "aws_ssoadmin_managed_policy_attachment" "{attach_res}" {{',
            f'  instance_arn       = aws_ssoadmin_permission_set.{resource_name}.instance_arn',
            f'  permission_set_arn = aws_ssoadmin_permission_set.{resource_name}.arn',
            f'  managed_policy_arn = "{policy_arn}"',
            f'}}',
            "",
        ]

    # Inline Policy (Customer Managed 통합)
    inline_resource_name = None
    if inline_doc is not None:
        inline_resource_name = f"{resource_name}_inline"
        # JSON을 Terraform heredoc으로 박지 않고 jsonencode로 안전하게
        # 하지만 통합된 dict를 그대로 박는 게 가장 안전 → heredoc 사용
        # heredoc 안의 JSON은 jsonencode 호출 없이 그대로 전달됨
        # Terraform이 문자열로 인식하므로 IIC API에 그대로 전송
        inline_json_indented = json.dumps(inline_doc, indent=2)

        parts += [
            f'resource "aws_ssoadmin_permission_set_inline_policy" "{inline_resource_name}" {{',
            f'  instance_arn       = aws_ssoadmin_permission_set.{resource_name}.instance_arn',
            f'  permission_set_arn = aws_ssoadmin_permission_set.{resource_name}.arn',
            f'  inline_policy = <<-EOT',
            inline_json_indented,
            f'EOT',
            f'}}',
            "",
        ]
        attachment_resource_names.append(
            ('aws_ssoadmin_permission_set_inline_policy', inline_resource_name)
        )

    # User data + Account Assignment
    if buf.requester_iic_user:
        depends_lines = [
            f'    {tf_type}.{name}'
            for tf_type, name in attachment_resource_names
        ]
        depends_block = ',\n'.join(depends_lines) if depends_lines else ''

        parts += [
            f'data "aws_identitystore_user" "{resource_name}_user" {{',
            f'  identity_store_id = tolist(data.aws_ssoadmin_instances.current.identity_store_ids)[0]',
            f'  alternate_identifier {{',
            f'    unique_attribute {{',
            f'      attribute_path  = "UserName"',
            f'      attribute_value = "{buf.requester_iic_user}"',
            f'    }}',
            f'  }}',
            f'}}',
            "",
            f'resource "aws_ssoadmin_account_assignment" "{resource_name}_assignment" {{',
            f'  instance_arn       = aws_ssoadmin_permission_set.{resource_name}.instance_arn',
            f'  permission_set_arn = aws_ssoadmin_permission_set.{resource_name}.arn',
            f'  target_id          = "{buf.target_account_id}"',
            f'  target_type        = "AWS_ACCOUNT"',
            f'  principal_id       = data.aws_identitystore_user.{resource_name}_user.user_id',
            f'  principal_type     = "USER"',
        ]
        if depends_block:
            parts += [
                f'  depends_on = [',
                depends_block,
                f'  ]',
            ]
        parts += [f'}}', ""]

    return '\n'.join(parts)


def write_workspace(
    buf: RoleBuffer,
    output_base: Path,
    fetcher: PolicyFetcher,
    inline_max_chars: int,
) -> Path:
    """RoleBuffer를 디스크에 워크스페이스로 저장. 저장된 디렉터리 반환."""
    out_dir = output_base / buf.account_id / buf.role_name
    out_dir.mkdir(parents=True, exist_ok=True)

    main_tf = generate_main_tf(buf, fetcher, inline_max_chars)

    files = {
        'providers.tf': PROVIDERS_TF,
        'data.tf': DATA_TF,
        'main.tf': main_tf,
    }
    for name, content in files.items():
        (out_dir / name).write_text(content, encoding='utf-8')
        logger.info(f"Saved: {out_dir / name}")

    meta = {
        'account_id': buf.account_id,
        'role_name': buf.role_name,
        'requester_iic_user': buf.requester_iic_user,
        'target_account_id': buf.target_account_id,
        'aws_managed_policies': sorted(
            p for p in buf.policy_arns if is_aws_managed_policy(p)
        ),
        'customer_managed_policies': sorted(
            p for p in buf.policy_arns if not is_aws_managed_policy(p)
        ),
        'first_event_at': buf.first_event_at.isoformat() if buf.first_event_at else None,
        'last_event_at': buf.last_event_at.isoformat() if buf.last_event_at else None,
        'processed_at': datetime.now(timezone.utc).isoformat(),
    }
    (out_dir / 'metadata.json').write_text(
        json.dumps(meta, indent=2, ensure_ascii=False), encoding='utf-8'
    )
    return out_dir
